import bcrypt from 'bcryptjs';
const data = {
  users: [
    {
      name: 'Nikita',
      email: 'nikita@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    {
      name: 'John Doe',
      email: 'user@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
  ],
  products: [
    {
      // _id: '1',
      image: ['/images/p1.jpg', '/images/p2.jpg'],
      name: 'Стелька orto',
      slug: 'stelka',
      category: 'стельки',
      articul: 'ae123hbj344j5h',
      size: '42',
      color: ['синий', 'бежевый'],
      length: '',
      price: 600,
      brand: 'ORTO',
      country: 'Германия',
      rating: 3.5,
      numReviews: 1,
      description: 'Описание стельки',
    },
    {
      // _id: '2',
      image: ['/images/p2.jpg'],
      name: 'Стелька correct',
      slug: 'stelka_correct',
      category: 'стельки',
      articul: 'ae123hbj344j5h',
      size: '42',
      color: ['бежевый'],
      length: '',
      price: 600,
      brand: 'ORTO',
      country: 'Германия',
      rating: 0,
      numReviews: 2,
      description: 'Описание стельки',
    },
    {
      // _id: '3',
      image: ['/images/p3.jpg'],
      name: 'Подушка ОРТО',
      slug: 'podyshka',
      category: 'ортопедические подушки',
      articul: 'ae123hbj374j5h',
      size: '',
      color: ['белый'],
      length: '19см * 15см',
      price: 2200,
      brand: 'ORTO',
      country: 'Германия',
      rating: 4,
      numReviews: 3,
      description: 'Описание подушки',
    },
    {
      // _id: '4',
      image: ['/images/p4.jpg'], //679 x 829
      name: 'Гольфы женские',
      slug: 'golf',
      category: 'гольфы',
      articul: 'ae123hbd344j5h',
      size: '42',
      color: ['синий'],
      length: '20см',
      price: 1200,
      brand: 'ORTO',
      country: 'Россия',
      rating: 0,
      numReviews: 4,
      description: 'Описание гольфов',
    },
  ],
};

export default data;
